version: 0.2 
 
env:
  git-credential-helper: yes

phases: 
  install: 
    runtime-versions: 
      nodejs: 10
  pre_build: 
    commands: 
      - echo Installing source NPM dependencies... 
      - npm install 
  build: 
    commands: 
      - echo Build started on `date` 
      - branch=$CODEBUILD_SOURCE_VERSION
      - echo Using branch $branch of target repositories
      - echo Compiling the Node.js code
      - npm run build
      - echo Running unit tests
      - npm test

  post_build: 
    commands: 
      - echo Build completed on `date` 
      - npm run integrationTest
      - echo Integration tests completed on `date`
