version: 0.2 
 
env:
  git-credential-helper: yes

phases: 
  install: 
    runtime-versions: 
      nodejs: 8
      nodejs: 10
  build: 
    commands:
      - node -v
      - n 8.0.0
      - node -v
